name: kalendar
description: Calendar utility that gives you access to multiple calendars.
version: 0.0.1-dev.1
homepage: https://github.com/ArkrootHQ/kalender

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:


